const video=document.getElementById('video');const status=document.getElementById('status');const title=document.getElementById('video-title');const list=document.getElementById('video-list');const count=document.getElementById('count');let videos=[];
const API='https://api.github.com/repos/mrtofsir2-wq/B4U-Video-Host/releases/tags/v0.1.0';
function cleanTitle(name){return name.replace(/\.mp4$/i,'').replace(/[_\.]+/g,' ').replace(/\s+/g,' ').trim().replace(/^From Klickpin com /i,'').replace(/^YTDown com YouTube /i,'');}
function playVideo(item){video.src=item.url;title.textContent=item.title;status.textContent='Loading…';video.load();video.play().catch(()=>{});document.querySelectorAll('.video-item').forEach(x=>x.classList.toggle('active',x.dataset.id===item.id));window.scrollTo({top:0,behavior:'smooth'});}
function makeThumb(item){const wrap=document.createElement('div');wrap.className='thumb';const t=document.createElement('video');t.className='thumb-video';t.src=item.url;t.muted=true;t.playsInline=true;t.preload='metadata';t.setAttribute('aria-hidden','true');const play=document.createElement('span');play.className='thumb-play';play.textContent='▶';wrap.append(t,play);t.addEventListener('loadedmetadata',()=>{if(Number.isFinite(t.duration)&&t.duration>0){t.currentTime=Math.max(0.1,t.duration*0.2);}});t.addEventListener('seeked',()=>{t.pause();});return wrap;}
function render(){count.textContent=`${videos.length} video${videos.length===1?'':'s'}`;list.innerHTML='';videos.forEach((item,i)=>{const card=document.createElement('button');card.className='video-item';card.dataset.id=item.id;card.appendChild(makeThumb(item));const meta=document.createElement('div');meta.className='meta';const strong=document.createElement('strong');strong.textContent=item.title;const small=document.createElement('small');small.textContent=item.description||'GitHub Release';meta.append(strong,small);card.appendChild(meta);card.addEventListener('click',()=>playVideo(item));list.appendChild(card);if(i===0)playVideo(item);});}
function loadFallback(){fetch('videos.json?cache='+Date.now()).then(r=>r.json()).then(data=>{videos=data;render();}).catch(()=>{status.textContent='Could not load video list';});}
fetch(API).then(r=>{if(!r.ok)throw new Error('GitHub API error');return r.json();}).then(release=>{videos=(release.assets||[]).filter(a=>a.content_type==='video/mp4'||/\.mp4$/i.test(a.name)).map(a=>({id:String(a.id),title:cleanTitle(a.name),description:'GitHub Release • '+(a.size/1048576).toFixed(1)+' MB',url:a.browser_download_url}));if(videos.length)render();else loadFallback();}).catch(loadFallback);
video.addEventListener('loadedmetadata',()=>{status.textContent=`Ready • ${Math.round(video.duration)}s`});video.addEventListener('play',()=>status.textContent='Playing');video.addEventListener('pause',()=>status.textContent='Paused');video.addEventListener('ended',()=>status.textContent='Finished');video.addEventListener('error',()=>status.textContent='Video could not be loaded');
